# Generated by Django 2.0.2 on 2018-03-10 20:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_create_contact_model'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contact',
            options={'ordering': ['name']},
        ),
    ]
